### Send POST request with json body
PUT http://localhost:3000/api/products
Content-Type: application/json

{
  "category": "Carro",
  "createdAt": "01/01/2024",
  "description": "Hilux SRV 4x4 3.0 CD Diesel 2015",
  "name": "Hilux SRV 4x4 3.0 CD Diesel 2015",
  "rating": 5.0
}